### ISSUE TITLE
MFMailComposeViewController freezes if I have ever used ZAActivityBar in App Cycle 

### ISSUE THREAD

**Issue by tariq235** [zacaltman/ZAActivityBar#13]
I am almost end of my app completion stage. So the resolution of this bug is very important for me. Cause I have used ZAActivityBar at many places.

Issue:

Lets say I have used [ZAActivityBar showWithStatus:@"Dummy"] at any place of the application and I have successfully dismissed it using dismiss method. So, the problem is in one of the screen I have to show MailComposer. I am just presenting mail compose view controller normally without any use of your activity bar. But my MFMailComposeViewController completely in freezing state. There is no way i can go back. I have to terminate at the end.

To verify this issue that this issue is due to the ZAActivityBar. I started my app again and I quickly navigated back to the screen where I am using MailComposer and at this time I have never used ZAActivityBar in App Life cycle so now its not freezing. It's working absolutely fine.

Please fix this issue asap. I am running in my Appstore submission week.

**Comment by zacaltman** [comment]
I think i've located the issue and fixed it. Testing it now...

**Comment by tariq235** [comment]
Great!!
Waiting for the new commit :)

For time being I have fixed the issue by  adding   [[ZAActivityBar sharedView] setHidden:YES]; on MFMailComposeViewController presentModal click action and I am again setting hidden as NO on MFMailComposer dismiss action

**Comment by tariq235** [comment]
Is there any update on this issue ?

**Comment by zacaltman** [comment]
Ahh, forgot to push. Coming shortly.

**Comment by ghost** [comment]
Hi, it still doesn't work.

**Comment by sagiwei** [comment]
MFMailComposeViewController freezed, it still doesn't work, why this issue be closed?

**Comment by sagiwei** [comment]
I added some code witch set the overlayWindow hidden to yes in method `- (void) dismiss` seem to fixed this bug.

``` objective-c
- (void) dismiss {
    dispatch_async(dispatch_get_main_queue(), ^{

            // add begin
            double delayInSeconds = duration;
            dispatch_time_t popTime = dispatch_time(DISPATCH_TIME_NOW, (int64_t)(delayInSeconds * NSEC_PER_SEC));
            dispatch_after(popTime, dispatch_get_main_queue(), ^(void){
                [self.overlayWindow setHidden:YES];
            });
            // add end
        }
    });
}
```

**Comment by ghost** [comment]
It's already fixed with the latest version

**Comment by sagiwei** [comment]
oh, great! I got it from the Pods, maybe the CocoaPods version is out of date.

**Comment by ghost** [comment]
Yeah, I think so too. anyways, it's working fine on my projects already. using the latest.
